### ISSUE TITLE
Sample of "Spatial operations" is sometimes not responding.

### ISSUE THREAD

**Issue by mahiran** [Esri/arcgis-runtime-samples-ios#465] opened 2018-08-22 06:11 UTC
**Application**: ArcGIS Runtime SDK Samples (iOS), downloaded from iTunes App store

**Device**: iPhone 7 Plus

**Operating System**: iOS 11.4.1

**Error Description**: Sample of "Spatial operations" is sometimes not responding.

**How to reproduce**: Categories -> GEOMETRY -> Spatial operations -> Choose operation -> tap any operation

**Comment by nixta** [comment] 2018-09-06 18:03
Hi @mahiran, thanks for reporting this.

I am unable to reproduce the issue. Could you provide a little more information please?

1. In what was does the app stop responding?
2. Can you give an indication of how frequently this stops responding? 1 time in 2, 1 in 10?
3. Is this downloaded from the App Store, or an app you have built yourself?

Thank you!

Nick.

**Comment by mahiran** [comment] 2018-09-06 23:05
Hi Nick,
Thank you for your response.

1 and 2. During my test, app did not stopped (or hanged up) even once.  Even though I selected any operation (Union, Difference, etc.), no operation executed (no red part displayed).
3. Only sometimes. (Just now I tried to reproduce it again, but I could not encountered with this issue)
4. I downloaded this "ArcGIS Runtime SDK Samples" app from iTunes App store.

Regards,
Masanobu

**Comment by nixta** [comment] 2018-09-06 23:08
Aha. I see. Thank you. That helps.

I'll keep trying to reproduce this. In the meantime, if you do see it happen again, please update this issue.

**Comment by mahiran** [comment] 2018-09-07 01:15
I was able to reproduce this issue. (Please refer the attached movie file)
[IMG_0510.zip](https://github.com/Esri/arcgis-runtime-samples-ios/files/2359177/IMG_0510.zip)

**Comment by nixta** [comment] 2018-09-07 13:39
Oh, excellent. Thanks for providing that @mahiran! Hugely helpful.

**Comment by nixta** [comment] 2019-01-14 16:42
Hi @mahiran. Is this still an issue for you with the current app?

**Comment by saratchandrakarumuri** [comment] 2019-02-08 01:19
I ran this sample for 150 times on a couple of devices and I encountered this issue only once on an iPhone 7

**Comment by yo1995** [comment] 2020-08-31 23:15
Hi @saratchandrakarumuri , I tried with our latest sample and it seems not to be reproducible. Can we close this issue?

Thanks.

**Comment by yo1995** [comment] 2020-09-11 18:17
I made further updates to this sample in #965 , and do not see this issue anymore.

**Comment by yo1995** [comment] 2020-11-19 17:34
Close due to inactivity. Feel free to reopen if the issue persists!

**Closed by yo1995** 2020-11-19 17:34 UTC
