### ISSUE TITLE
exportImageWithCompletion Not found when i used ArcGis Map in swift 3.0

### ISSUE THREAD

**Issue by shahchirag2110** [Esri/arcgis-runtime-samples-ios#229] opened 2016-11-19 14:20 UTC
**I wrote code like this . I need this thing working urgently . Please help me**

```
self.mapView.exportImageWithCompletion { [weak self] (image:UIImage?, error:NSError?) -> Void in
            if let error = error {
                UIAlertView(title: "Error", message: error.localizedDescription, delegate: nil, cancelButtonTitle: "Ok").show()
            }
            if let image = image {
                //on completion imitate flash

            }
        }
```
But in swift 3.0 this method not found see the screen shot
![screen shot 2016-11-19 at 7 49 15 pm](https://cloud.githubusercontent.com/assets/11793894/20456046/5aa1518a-ae91-11e6-8979-e8334a37ce1e.png)

**Comment by singhgag** [comment] 2016-11-21 17:38
Try removing the `WithCompletion` from method name. Or simply start fresh, see if you get the method in the intelli-sense when you do a `mapView.`.

**Comment by singhgag** [comment] 2016-11-21 17:39
I am including a snippet thats working for me.

```
self.mapView.exportImage { [weak self] (image:UIImage?, error:NSError?) -> Void in
            if let error = error {
                UIAlertView(title: "Error", message: error.localizedDescription, delegate: nil, cancelButtonTitle: "Ok").show()
            }
            if let image = image {
                //on completion imitate flash
                self?.imitateFlash(image)
            }
        }
```

**Comment by shahchirag2110** [comment] 2016-11-22 11:40
@singhgag Thank for reply but same error look the screenshot and if start fresh method not found i am not getting the method in intelli-sense of xcode 

 ```
 self.mapView.exportImage { [weak self] (image:UIImage?, error:NSError?) -> Void in
            if error != nil{
                UIAlertView(title: "Error", message: error.localizedDescription, delegate: nil, cancelButtonTitle: "Ok").show()
            }
            if let image = image {
                //on completion imitate flash
//                self?.imitateFlash(image)
            }
        }
```

**In intelli-sense below method i got**
![screen shot 2016-11-22 at 5 08 52 pm](https://cloud.githubusercontent.com/assets/11793894/20522460/72f54d08-b0d6-11e6-87ab-749cbe536fed.png)
**And error something like below**
![screen shot 2016-11-22 at 5 08 20 pm](https://cloud.githubusercontent.com/assets/11793894/20522467/7bca9ac8-b0d6-11e6-8a11-d737343ae26e.png)

**Comment by shahchirag2110** [comment] 2016-11-22 11:51
@singhgag did import any thing in file i import only ArcGIS and i am coding in Xcode 8 and swift 3.0

**Comment by maryharvey** [comment] 2016-11-22 12:09
@shahchirag2110 Apologies if you have already tried this.
So the problem is that intellisense (auto-complete) is not picking up the ArcGIS API. I experienced this a few times and solved it by closing all open projects and Quiting Xcode. On reopening the project auto-complete operated correctly. 
![2016-11-22_11-52-18](https://cloud.githubusercontent.com/assets/3710427/20523260/1923b80c-b0ac-11e6-8796-84b4e6b13ef8.png)

**Comment by shahchirag2110** [comment] 2016-11-22 12:20
@maryharvey  I tried it 2 to 3 times but it is not working any how

**Comment by maryharvey** [comment] 2016-11-22 13:21
@shahchirag2110 This sounds like a general problem with your auto-complete (not specific to the Samples)... if you agree you could transfer this query to the geonet channel? https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios ?
Please state the version of Xcode and Swift.

**Comment by dlednik** [comment] 2017-01-11 10:47
Just a note on the original code. `NSError` has been replaced with `Error` class in Swift 3.x, that is why compiler is complaining. 

I found it's best not to include type in blocks to avoid this issues in the future:

```Swift
self.mapView.exportImageWithCompletion { [weak self] (image, error) -> Void in
            if let error = error {
                UIAlertView(title: "Error", message: error.localizedDescription, delegate: nil, cancelButtonTitle: "Ok").show()
            }
            if let image = image {
                //on completion imitate flash

            }
        }
```

**Comment by dg0yal** [comment] 2017-02-06 19:13
Here is the swift 3 usage - https://github.com/Esri/arcgis-runtime-samples-ios/blob/18570eca866320d233b8e57cfc7136d1172f6d4a/arcgis-ios-sdk-samples/Maps/Take%20screenshot/MapViewScreenshotViewController.swift#L74

**Closed by dg0yal** 2017-02-06 19:13 UTC
